# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
configHash: "1" # configuration change detection
codenow:
  instance: ""
  applicationName: ""
  applicationRuntimeName: ""
  applicationVersion: ""
  componentRuntimeName: "omi-new-net"
  componentName: "omi-new-net"
  componentVersion: ${project.version}
  templateId: ""
  domainName: "release-test.codenow-preview.com"
  environmentId: ""

buildNumber: "${env.BUILD_NUMBER}"

image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  externalEndpointEnabled: true

metricsPrometheusEnabled: true
metricsPrometheusStep: PT1M

fluentbit:
  istioProxy:
    enabled: true
    parser: envoy-logging-filter-parser
  parser: oxus-app-component-json

configFiles: {}
environmentVariables: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

upperCase: true
